# PART C

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('concrete_data.csv')
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
df.shape

(1030, 9)

In [4]:
df.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [5]:
concrete_data_columns = df.columns

X = df[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
Y = df['Strength']

In [6]:
X_norm = (X - X.mean()) / X.std()
X_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [7]:
n_cols = X_norm.shape[1]
n_cols

8

In [8]:
import keras

WARNING:tensorflow:From C:\Users\ashut\anaconda3\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [9]:
from keras.models import Sequential
from keras.layers import Dense

In [10]:
def regression_model():
    
    model=Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_norm, Y, test_size=0.3, random_state=42)

In [12]:
model = regression_model()

WARNING:tensorflow:From C:\Users\ashut\anaconda3\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From C:\Users\ashut\anaconda3\lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [16]:
epochs = 100
model.fit(X_train, Y_train, epochs=epochs, verbose=2)

Epoch 1/100
23/23 - 0s - loss: 127.2251 - 46ms/epoch - 2ms/step
Epoch 2/100
23/23 - 0s - loss: 126.5598 - 36ms/epoch - 2ms/step
Epoch 3/100
23/23 - 0s - loss: 125.9051 - 37ms/epoch - 2ms/step
Epoch 4/100
23/23 - 0s - loss: 125.2997 - 37ms/epoch - 2ms/step
Epoch 5/100
23/23 - 0s - loss: 124.6263 - 38ms/epoch - 2ms/step
Epoch 6/100
23/23 - 0s - loss: 123.9901 - 39ms/epoch - 2ms/step
Epoch 7/100
23/23 - 0s - loss: 123.2948 - 37ms/epoch - 2ms/step
Epoch 8/100
23/23 - 0s - loss: 122.6551 - 37ms/epoch - 2ms/step
Epoch 9/100
23/23 - 0s - loss: 122.0188 - 40ms/epoch - 2ms/step
Epoch 10/100
23/23 - 0s - loss: 121.3960 - 42ms/epoch - 2ms/step
Epoch 11/100
23/23 - 0s - loss: 120.7017 - 35ms/epoch - 2ms/step
Epoch 12/100
23/23 - 0s - loss: 120.1801 - 40ms/epoch - 2ms/step
Epoch 13/100
23/23 - 0s - loss: 119.4083 - 41ms/epoch - 2ms/step
Epoch 14/100
23/23 - 0s - loss: 118.7588 - 41ms/epoch - 2ms/step
Epoch 15/100
23/23 - 0s - loss: 118.1023 - 36ms/epoch - 2ms/step
Epoch 16/100
23/23 - 0s - loss: 117.4652 - 40ms/epoch - 2ms/step
Epoch 17/100
23/23 - 0s - loss: 116.8163 - 39ms/epoch - 2ms/step
Epoch 18/100
23/23 - 0s - loss: 116.2593 - 39ms/epoch - 2ms/step
Epoch 19/100
23/23 - 0s - loss: 115.6185 - 39ms/epoch - 2ms/step
Epoch 20/100
23/23 - 0s - loss: 114.8800 - 39ms/epoch - 2ms/step
Epoch 21/100
23/23 - 0s - loss: 114.2301 - 38ms/epoch - 2ms/step
Epoch 22/100
23/23 - 0s - loss: 113.6418 - 40ms/epoch - 2ms/step
Epoch 23/100
23/23 - 0s - loss: 113.0367 - 37ms/epoch - 2ms/step
Epoch 24/100
23/23 - 0s - loss: 112.3566 - 40ms/epoch - 2ms/step
Epoch 25/100
23/23 - 0s - loss: 111.7842 - 35ms/epoch - 2ms/step
Epoch 26/100
23/23 - 0s - loss: 111.1530 - 32ms/epoch - 1ms/step
Epoch 27/100
23/23 - 0s - loss: 110.5314 - 38ms/epoch - 2ms/step
Epoch 28/100
23/23 - 0s - loss: 109.8474 - 32ms/epoch - 1ms/step
Epoch 29/100
23/23 - 0s - loss: 109.3354 - 40ms/epoch - 2ms/step
Epoch 30/100
23/23 - 0s - loss: 108.6196 - 39ms/epoch - 2ms/step
Epoch 31/100
23/23 - 0s - loss: 108.0113 - 39ms/epoch - 2ms/step
Epoch 32/100
23/23 - 0s - loss: 107.4635 - 36ms/epoch - 2ms/step
Epoch 33/100
23/23 - 0s - loss: 106.8340 - 37ms/epoch - 2ms/step
Epoch 34/100
23/23 - 0s - loss: 106.1946 - 37ms/epoch - 2ms/step
Epoch 35/100
23/23 - 0s - loss: 105.6224 - 41ms/epoch - 2ms/step
Epoch 36/100
23/23 - 0s - loss: 105.0124 - 39ms/epoch - 2ms/step
Epoch 37/100
23/23 - 0s - loss: 104.4038 - 41ms/epoch - 2ms/step
Epoch 38/100
23/23 - 0s - loss: 103.8668 - 39ms/epoch - 2ms/step
Epoch 39/100
23/23 - 0s - loss: 103.1712 - 37ms/epoch - 2ms/step
Epoch 40/100
23/23 - 0s - loss: 102.6731 - 28ms/epoch - 1ms/step
Epoch 41/100
23/23 - 0s - loss: 102.0443 - 36ms/epoch - 2ms/step
Epoch 42/100
23/23 - 0s - loss: 101.4962 - 38ms/epoch - 2ms/step
Epoch 43/100
23/23 - 0s - loss: 100.8255 - 38ms/epoch - 2ms/step
Epoch 44/100
23/23 - 0s - loss: 100.2959 - 42ms/epoch - 2ms/step
Epoch 45/100
23/23 - 0s - loss: 99.6432 - 43ms/epoch - 2ms/step
Epoch 46/100
23/23 - 0s - loss: 99.0731 - 42ms/epoch - 2ms/step
Epoch 47/100
23/23 - 0s - loss: 98.5615 - 34ms/epoch - 1ms/step
Epoch 48/100
23/23 - 0s - loss: 97.9498 - 43ms/epoch - 2ms/step
Epoch 49/100
23/23 - 0s - loss: 97.4611 - 42ms/epoch - 2ms/step
Epoch 50/100
23/23 - 0s - loss: 96.8536 - 37ms/epoch - 2ms/step
Epoch 51/100
23/23 - 0s - loss: 96.3297 - 32ms/epoch - 1ms/step
Epoch 52/100
23/23 - 0s - loss: 95.8095 - 41ms/epoch - 2ms/step
Epoch 53/100
23/23 - 0s - loss: 95.2817 - 41ms/epoch - 2ms/step
Epoch 54/100
23/23 - 0s - loss: 94.7806 - 40ms/epoch - 2ms/step
Epoch 55/100
23/23 - 0s - loss: 94.3044 - 43ms/epoch - 2ms/step
Epoch 56/100
23/23 - 0s - loss: 93.7850 - 37ms/epoch - 2ms/step
Epoch 57/100
23/23 - 0s - loss: 93.2746 - 41ms/epoch - 2ms/step
Epoch 58/100
23/23 - 0s - loss: 92.8110 - 38ms/epoch - 2ms/step
Epoch 59/100
23/23 - 0s - loss: 92.2854 - 37ms/epoch - 2ms/step
Epoch 60/100
23/23 - 0s - loss: 91.7523 - 39ms/epoch - 2ms/step
Epoch 61/100
23/23 - 0s - loss: 91.2155 - 38ms/epoch - 2ms/step
Epoch 62/100
23/23 - 0s - loss: 90.7874 - 31ms/epoch - 1ms/step
Epoch 63/100
23/23 - 0s - loss: 90.2851 - 40ms/epoch - 2ms/step
Epoch 64/100
23/23 - 0s - loss: 89.7760 - 38ms/epoch - 2ms/step
Epoch 65/100
23/23 - 0s - loss: 89.3520 - 37ms/epoch - 2ms/step
Epoch 66/100
23/23 - 0s - loss: 88.8044 - 36ms/epoch - 2ms/step
Epoch 67/100
23/23 - 0s - loss: 88.3662 - 45ms/epoch - 2ms/step
Epoch 68/100
23/23 - 0s - loss: 87.9290 - 40ms/epoch - 2ms/step
Epoch 69/100
23/23 - 0s - loss: 87.5281 - 37ms/epoch - 2ms/step
Epoch 70/100
23/23 - 0s - loss: 87.0006 - 36ms/epoch - 2ms/step
Epoch 71/100
23/23 - 0s - loss: 86.6384 - 36ms/epoch - 2ms/step
Epoch 72/100
23/23 - 0s - loss: 86.1311 - 38ms/epoch - 2ms/step
Epoch 73/100
23/23 - 0s - loss: 85.7629 - 36ms/epoch - 2ms/step
Epoch 74/100
23/23 - 0s - loss: 85.2965 - 35ms/epoch - 2ms/step
Epoch 75/100
23/23 - 0s - loss: 84.8358 - 28ms/epoch - 1ms/step
Epoch 76/100
23/23 - 0s - loss: 84.4331 - 28ms/epoch - 1ms/step
Epoch 77/100
23/23 - 0s - loss: 83.9575 - 37ms/epoch - 2ms/step
Epoch 78/100
23/23 - 0s - loss: 83.5376 - 37ms/epoch - 2ms/step
Epoch 79/100
23/23 - 0s - loss: 83.0717 - 37ms/epoch - 2ms/step
Epoch 80/100
23/23 - 0s - loss: 82.6508 - 37ms/epoch - 2ms/step
Epoch 81/100
23/23 - 0s - loss: 82.2207 - 39ms/epoch - 2ms/step
Epoch 82/100
23/23 - 0s - loss: 81.8472 - 36ms/epoch - 2ms/step
Epoch 83/100
23/23 - 0s - loss: 81.4077 - 37ms/epoch - 2ms/step
Epoch 84/100
23/23 - 0s - loss: 80.9949 - 24ms/epoch - 1ms/step
Epoch 85/100
23/23 - 0s - loss: 80.5523 - 26ms/epoch - 1ms/step
Epoch 86/100
23/23 - 0s - loss: 80.1081 - 39ms/epoch - 2ms/step
Epoch 87/100
23/23 - 0s - loss: 79.7336 - 37ms/epoch - 2ms/step
Epoch 88/100
23/23 - 0s - loss: 79.2999 - 39ms/epoch - 2ms/step
Epoch 89/100
23/23 - 0s - loss: 78.8861 - 33ms/epoch - 1ms/step
Epoch 90/100
23/23 - 0s - loss: 78.5637 - 38ms/epoch - 2ms/step
Epoch 91/100
23/23 - 0s - loss: 78.1790 - 36ms/epoch - 2ms/step
Epoch 92/100
23/23 - 0s - loss: 77.7393 - 38ms/epoch - 2ms/step
Epoch 93/100
23/23 - 0s - loss: 77.3592 - 41ms/epoch - 2ms/step
Epoch 94/100
23/23 - 0s - loss: 77.0095 - 38ms/epoch - 2ms/step
Epoch 95/100
23/23 - 0s - loss: 76.6116 - 35ms/epoch - 2ms/step
Epoch 96/100
23/23 - 0s - loss: 76.3484 - 37ms/epoch - 2ms/step
Epoch 97/100
23/23 - 0s - loss: 75.9260 - 35ms/epoch - 2ms/step
Epoch 98/100
23/23 - 0s - loss: 75.5865 - 38ms/epoch - 2ms/step
Epoch 99/100
23/23 - 0s - loss: 75.1946 - 35ms/epoch - 2ms/step
Epoch 100/100
23/23 - 0s - loss: 74.8017 - 32ms/epoch - 1ms/step

In [17]:
Y_pred = model.predict(X_test)

10/10 [==============================] - 0s 3ms/step

In [18]:
eval_model = model.evaluate(X_test, Y_test)
eval_model

10/10 [==============================] - 0s 2ms/step - loss: 82.8893

82.88931274414062

In [19]:
from sklearn.metrics import mean_squared_error

In [20]:
mse = mean_squared_error(Y_test, Y_pred)
mean_mse = np.mean(mse)
std_mse = np.std(mse)
print("Mean of Mean_Squared_Error: ", mean_mse)
print("Squared of Mean_Squared_Error: ", std_mse)

Mean of Mean_Squared_Error:  82.88931097565988
Squared of Mean_Squared_Error:  0.0

In [21]:
total_mse = 50
epochs = 100
mse_values = []
for i in range(0, total_mse):
    X_train, X_test, Y_train, Y_test = train_test_split(X_norm, Y, test_size = 0.3, random_state=i)
    model.fit(X_train, Y_train, epochs=epochs, verbose=0)
    MSE_eval = model.evaluate(X_test, Y_test, verbose=0)
    print("MSE "+str(i+1)+': '+str(MSE_eval))
    Y_prediction = model.predict(X_test)
    mse = mean_squared_error(Y_test, Y_prediction)
    mse_values.append(mse)
    
mean_mse = np.mean(mse)
std_mse = np.std(mse)

print("Mean of Mean Squared Error: ",str(mean_mse))
print("Standard Deviation of Mean Squared Error: ",str(std_mse))

MSE 1: 51.43818283081055
10/10 [==============================] - 0s 2ms/step
MSE 2: 55.988224029541016
10/10 [==============================] - 0s 2ms/step
MSE 3: 35.48197555541992
10/10 [==============================] - 0s 2ms/step
MSE 4: 41.424346923828125
10/10 [==============================] - 0s 2ms/step
MSE 5: 41.65070724487305
10/10 [==============================] - 0s 2ms/step
MSE 6: 43.69487762451172
10/10 [==============================] - 0s 1ms/step
MSE 7: 45.99861526489258
10/10 [==============================] - 0s 2ms/step
MSE 8: 37.12468338012695
10/10 [==============================] - 0s 2ms/step
MSE 9: 39.05061721801758
10/10 [==============================] - 0s 2ms/step
MSE 10: 40.33182907104492
10/10 [==============================] - 0s 2ms/step
MSE 11: 40.117313385009766
10/10 [==============================] - 0s 2ms/step
MSE 12: 36.28202438354492
10/10 [==============================] - 0s 2ms/step
MSE 13: 44.898765563964844
10/10 [==============================] - 0s 2ms/step
MSE 14: 44.19528579711914
10/10 [==============================] - 0s 2ms/step
MSE 15: 36.057167053222656
10/10 [==============================] - 0s 409us/step
MSE 16: 30.830535888671875
10/10 [==============================] - 0s 3ms/step
MSE 17: 35.38950729370117
10/10 [==============================] - 0s 3ms/step
MSE 18: 36.57613754272461
10/10 [==============================] - 0s 1ms/step
MSE 19: 34.94171142578125
10/10 [==============================] - 0s 3ms/step
MSE 20: 37.59214782714844
10/10 [==============================] - 0s 3ms/step
MSE 21: 32.603729248046875
10/10 [==============================] - 0s 1ms/step
MSE 22: 35.79509735107422
10/10 [==============================] - 0s 2ms/step
MSE 23: 32.13968276977539
10/10 [==============================] - 0s 2ms/step
MSE 24: 36.89609909057617
10/10 [==============================] - 0s 2ms/step
MSE 25: 38.15673828125
10/10 [==============================] - 0s 2ms/step
MSE 26: 36.7236213684082
10/10 [==============================] - 0s 2ms/step
MSE 27: 32.77595138549805
10/10 [==============================] - 0s 2ms/step
MSE 28: 29.845333099365234
10/10 [==============================] - 0s 2ms/step
MSE 29: 38.91724395751953
10/10 [==============================] - 0s 2ms/step
MSE 30: 39.04330062866211
10/10 [==============================] - 0s 2ms/step
MSE 31: 33.88934326171875
10/10 [==============================] - 0s 2ms/step
MSE 32: 31.7818660736084
10/10 [==============================] - 0s 2ms/step
MSE 33: 33.45305252075195
10/10 [==============================] - 0s 2ms/step
MSE 34: 36.364540100097656
10/10 [==============================] - 0s 2ms/step
MSE 35: 36.624324798583984
10/10 [==============================] - 0s 2ms/step
MSE 36: 42.66166305541992
10/10 [==============================] - 0s 2ms/step
MSE 37: 33.07072830200195
10/10 [==============================] - 0s 2ms/step
MSE 38: 37.75358200073242
10/10 [==============================] - 0s 2ms/step
MSE 39: 36.22848892211914
10/10 [==============================] - 0s 1ms/step
MSE 40: 29.157564163208008
10/10 [==============================] - 0s 2ms/step
MSE 41: 38.79104995727539
10/10 [==============================] - 0s 792us/step
MSE 42: 30.71454429626465
10/10 [==============================] - 0s 1ms/step
MSE 43: 32.822715759277344
10/10 [==============================] - 0s 3ms/step
MSE 44: 36.654090881347656
10/10 [==============================] - 0s 2ms/step
MSE 45: 36.379634857177734
10/10 [==============================] - 0s 2ms/step
MSE 46: 36.756195068359375
10/10 [==============================] - 0s 2ms/step
MSE 47: 35.28770065307617
10/10 [==============================] - 0s 3ms/step
MSE 48: 34.06695556640625
10/10 [==============================] - 0s 1ms/step
MSE 49: 35.96997833251953
10/10 [==============================] - 0s 1ms/step
MSE 50: 37.51993179321289
10/10 [==============================] - 0s 1ms/step
Mean of Mean Squared Error:  37.51993135142726
Standard Deviation of Mean Squared Error:  0.0