# PART-A

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("concrete_data.csv")

In [3]:
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [4]:
df.shape

(1030, 9)

In [5]:
df.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [19]:
concrete_data_columns = df.columns

X = df[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
Y = df['Strength']

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=4)

In [21]:
import keras

In [22]:
from keras.models import Sequential
from keras.layers import Dense

In [23]:
def regression_model():
    
    model=Sequential()
    model.add(Dense(10, activation='relu', input_shape=(X_train.shape[1],)))
    model.add(Dense(1))
    
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [24]:
model = regression_model()

In [27]:
model.fit(X_train, Y_train, validation_split=0.3, epochs=50, verbose=2)

Epoch 1/50
16/16 - 0s - loss: 108.9568 - val_loss: 100.7897 - 131ms/epoch - 8ms/step
Epoch 2/50
16/16 - 0s - loss: 107.2136 - val_loss: 99.3472 - 77ms/epoch - 5ms/step
Epoch 3/50
16/16 - 0s - loss: 105.6823 - val_loss: 99.1696 - 68ms/epoch - 4ms/step
Epoch 4/50
16/16 - 0s - loss: 104.7058 - val_loss: 100.4830 - 71ms/epoch - 4ms/step
Epoch 5/50
16/16 - 0s - loss: 106.1012 - val_loss: 99.6017 - 75ms/epoch - 5ms/step
Epoch 6/50
16/16 - 0s - loss: 105.8808 - val_loss: 99.0986 - 71ms/epoch - 4ms/step
Epoch 7/50
16/16 - 0s - loss: 106.5125 - val_loss: 108.0719 - 72ms/epoch - 4ms/step
Epoch 8/50
16/16 - 0s - loss: 105.8170 - val_loss: 98.4881 - 69ms/epoch - 4ms/step
Epoch 9/50
16/16 - 0s - loss: 104.7381 - val_loss: 97.7250 - 69ms/epoch - 4ms/step
Epoch 10/50
16/16 - 0s - loss: 104.3913 - val_loss: 97.4941 - 76ms/epoch - 5ms/step
Epoch 11/50
16/16 - 0s - loss: 103.1224 - val_loss: 99.5969 - 80ms/epoch - 5ms/step
Epoch 12/50
16/16 - 0s - loss: 104.2461 - val_loss: 97.8763 - 71ms/epoch - 4ms/step
Epoch 13/50
16/16 - 0s - loss: 103.6431 - val_loss: 99.2767 - 74ms/epoch - 5ms/step
Epoch 14/50
16/16 - 0s - loss: 106.1128 - val_loss: 106.9443 - 75ms/epoch - 5ms/step
Epoch 15/50
16/16 - 0s - loss: 105.9363 - val_loss: 99.5387 - 70ms/epoch - 4ms/step
Epoch 16/50
16/16 - 0s - loss: 103.1076 - val_loss: 96.8360 - 74ms/epoch - 5ms/step
Epoch 17/50
16/16 - 0s - loss: 103.6262 - val_loss: 98.4915 - 76ms/epoch - 5ms/step
Epoch 18/50
16/16 - 0s - loss: 106.1763 - val_loss: 97.4308 - 77ms/epoch - 5ms/step
Epoch 19/50
16/16 - 0s - loss: 106.2819 - val_loss: 98.3298 - 68ms/epoch - 4ms/step
Epoch 20/50
16/16 - 0s - loss: 106.0228 - val_loss: 97.5142 - 78ms/epoch - 5ms/step
Epoch 21/50
16/16 - 0s - loss: 104.4824 - val_loss: 96.1331 - 73ms/epoch - 5ms/step
Epoch 22/50
16/16 - 0s - loss: 102.2467 - val_loss: 95.9929 - 70ms/epoch - 4ms/step
Epoch 23/50
16/16 - 0s - loss: 103.5876 - val_loss: 97.4385 - 69ms/epoch - 4ms/step
Epoch 24/50
16/16 - 0s - loss: 104.0262 - val_loss: 96.1382 - 74ms/epoch - 5ms/step
Epoch 25/50
16/16 - 0s - loss: 102.1729 - val_loss: 97.4479 - 77ms/epoch - 5ms/step
Epoch 26/50
16/16 - 0s - loss: 102.7675 - val_loss: 96.3616 - 77ms/epoch - 5ms/step
Epoch 27/50
16/16 - 0s - loss: 102.2740 - val_loss: 98.5704 - 71ms/epoch - 4ms/step
Epoch 28/50
16/16 - 0s - loss: 103.2355 - val_loss: 102.3694 - 67ms/epoch - 4ms/step
Epoch 29/50
16/16 - 0s - loss: 102.4503 - val_loss: 95.9002 - 61ms/epoch - 4ms/step
Epoch 30/50
16/16 - 0s - loss: 106.0615 - val_loss: 99.5363 - 69ms/epoch - 4ms/step
Epoch 31/50
16/16 - 0s - loss: 102.8591 - val_loss: 95.6452 - 66ms/epoch - 4ms/step
Epoch 32/50
16/16 - 0s - loss: 101.2836 - val_loss: 95.5955 - 65ms/epoch - 4ms/step
Epoch 33/50
16/16 - 0s - loss: 101.4103 - val_loss: 95.3332 - 64ms/epoch - 4ms/step
Epoch 34/50
16/16 - 0s - loss: 101.9968 - val_loss: 98.5339 - 64ms/epoch - 4ms/step
Epoch 35/50
16/16 - 0s - loss: 102.2059 - val_loss: 95.1828 - 67ms/epoch - 4ms/step
Epoch 36/50
16/16 - 0s - loss: 101.5925 - val_loss: 96.5567 - 67ms/epoch - 4ms/step
Epoch 37/50
16/16 - 0s - loss: 101.7637 - val_loss: 97.8342 - 65ms/epoch - 4ms/step
Epoch 38/50
16/16 - 0s - loss: 101.3447 - val_loss: 97.1209 - 67ms/epoch - 4ms/step
Epoch 39/50
16/16 - 0s - loss: 103.2087 - val_loss: 96.8985 - 65ms/epoch - 4ms/step
Epoch 40/50
16/16 - 0s - loss: 102.0598 - val_loss: 94.7106 - 65ms/epoch - 4ms/step
Epoch 41/50
16/16 - 0s - loss: 102.2793 - val_loss: 95.2374 - 68ms/epoch - 4ms/step
Epoch 42/50
16/16 - 0s - loss: 100.5102 - val_loss: 95.8672 - 70ms/epoch - 4ms/step
Epoch 43/50
16/16 - 0s - loss: 101.5195 - val_loss: 95.2480 - 67ms/epoch - 4ms/step
Epoch 44/50
16/16 - 0s - loss: 101.6791 - val_loss: 94.2839 - 72ms/epoch - 4ms/step
Epoch 45/50
16/16 - 0s - loss: 103.2919 - val_loss: 95.3243 - 69ms/epoch - 4ms/step
Epoch 46/50
16/16 - 0s - loss: 102.1936 - val_loss: 102.3280 - 64ms/epoch - 4ms/step
Epoch 47/50
16/16 - 0s - loss: 105.5112 - val_loss: 114.8275 - 70ms/epoch - 4ms/step
Epoch 48/50
16/16 - 0s - loss: 111.8141 - val_loss: 104.9713 - 64ms/epoch - 4ms/step
Epoch 49/50
16/16 - 0s - loss: 104.9604 - val_loss: 96.0028 - 67ms/epoch - 4ms/step
Epoch 50/50
16/16 - 0s - loss: 101.4211 - val_loss: 93.9017 - 64ms/epoch - 4ms/step

In [43]:
Y_pred = model.predict(X_test)

10/10 [==============================] - 0s 2ms/step

In [41]:
eval_model = model.evaluate(X_test, Y_test)
eval_model

10/10 [==============================] - 0s 2ms/step - loss: 110.9204

110.92037963867188

In [44]:
from sklearn.metrics import mean_squared_error

In [48]:
mse = mean_squared_error(Y_test, Y_pred)
mean_mse = np.mean(mse)
std_mse = np.std(mse)
print("Mean of Mean_Squared_Error: ", mean_mse)
print("Squared of Mean_Squared_Error: ", std_mse)

Mean of Mean_Squared_Error:  110.9203852159265
Squared of Mean_Squared_Error:  0.0

In [63]:
total_mse = 50
epochs = 50
mse_values = []
for i in range(0, total_mse):
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state=i)
    model.fit(X_train, Y_train, epochs=epochs, verbose=0)
    MSE_eval = model.evaluate(X_test, Y_test, verbose=0)
    print("MSE "+str(i+1)+': '+str(MSE_eval))
    Y_prediction = model.predict(X_test)
    mse = mean_squared_error(Y_test, Y_prediction)
    mse_values.append(mse)
    
mean_mse = np.mean(mse)
std_mse = np.std(mse)

print("Mean of Mean Squared Error: ",str(mean_mse))
print("Standard Deviation of Mean Squared Error: ",str(std_mse))

MSE 1: 52.56545639038086
10/10 [==============================] - 0s 2ms/step
MSE 2: 55.01434326171875
10/10 [==============================] - 0s 875us/step
MSE 3: 43.86459732055664
10/10 [==============================] - 0s 2ms/step
MSE 4: 47.46037292480469
10/10 [==============================] - 0s 1ms/step
MSE 5: 46.6677131652832
10/10 [==============================] - 0s 1ms/step
MSE 6: 47.125404357910156
10/10 [==============================] - 0s 1ms/step
MSE 7: 57.78013229370117
10/10 [==============================] - 0s 2ms/step
MSE 8: 41.010528564453125
10/10 [==============================] - 0s 1ms/step
MSE 9: 53.99850082397461
10/10 [==============================] - 0s 1ms/step
MSE 10: 47.2817497253418
10/10 [==============================] - 0s 1ms/step
MSE 11: 44.15211486816406
10/10 [==============================] - 0s 1ms/step
MSE 12: 44.75056076049805
10/10 [==============================] - 0s 1ms/step
MSE 13: 51.134178161621094
10/10 [==============================] - 0s 2ms/step
MSE 14: 49.14444351196289
10/10 [==============================] - 0s 1ms/step
MSE 15: 46.917510986328125
10/10 [==============================] - 0s 1ms/step
MSE 16: 42.20114517211914
10/10 [==============================] - 0s 1ms/step
MSE 17: 43.810211181640625
10/10 [==============================] - 0s 2ms/step
MSE 18: 48.907135009765625
10/10 [==============================] - 0s 1ms/step
MSE 19: 42.87424087524414
10/10 [==============================] - 0s 1ms/step
MSE 20: 45.69852828979492
10/10 [==============================] - 0s 1ms/step
MSE 21: 41.84809494018555
10/10 [==============================] - 0s 1ms/step
MSE 22: 44.0599365234375
10/10 [==============================] - 0s 979us/step
MSE 23: 49.76521301269531
10/10 [==============================] - 0s 1ms/step
MSE 24: 43.817848205566406
10/10 [==============================] - 0s 795us/step
MSE 25: 55.164329528808594
10/10 [==============================] - 0s 1ms/step
MSE 26: 49.77275466918945
10/10 [==============================] - 0s 1ms/step
MSE 27: 47.89406204223633
10/10 [==============================] - 0s 2ms/step
MSE 28: 41.67182540893555
10/10 [==============================] - 0s 1ms/step
MSE 29: 50.900150299072266
10/10 [==============================] - 0s 1ms/step
MSE 30: 45.031227111816406
10/10 [==============================] - 0s 1ms/step
MSE 31: 47.06022262573242
10/10 [==============================] - 0s 1ms/step
MSE 32: 39.65884017944336
10/10 [==============================] - 0s 1ms/step
MSE 33: 43.34264373779297
10/10 [==============================] - 0s 1ms/step
MSE 34: 47.36617660522461
10/10 [==============================] - 0s 1ms/step
MSE 35: 47.278831481933594
10/10 [==============================] - 0s 896us/step
MSE 36: 59.58546447753906
10/10 [==============================] - 0s 1ms/step
MSE 37: 48.29392623901367
10/10 [==============================] - 0s 1ms/step
MSE 38: 51.37702178955078
10/10 [==============================] - 0s 1ms/step
MSE 39: 42.88718795776367
10/10 [==============================] - 0s 959us/step
MSE 40: 42.477352142333984
10/10 [==============================] - 0s 1ms/step
MSE 41: 50.53173065185547
10/10 [==============================] - 0s 1ms/step
MSE 42: 43.538414001464844
10/10 [==============================] - 0s 1ms/step
MSE 43: 45.68417739868164
10/10 [==============================] - 0s 1ms/step
MSE 44: 49.05834197998047
10/10 [==============================] - 0s 1ms/step
MSE 45: 51.356197357177734
10/10 [==============================] - 0s 837us/step
MSE 46: 52.99251174926758
10/10 [==============================] - 0s 1ms/step
MSE 47: 47.96846389770508
10/10 [==============================] - 0s 1ms/step
MSE 48: 47.472679138183594
10/10 [==============================] - 0s 1ms/step
MSE 49: 46.50468826293945
10/10 [==============================] - 0s 1ms/step
MSE 50: 49.358848571777344
10/10 [==============================] - 0s 1ms/step
Mean of Mean Squared Error:  49.358850477536684
Standard Deviation of Mean Squared Error:  0.0